Made More Universal: - Added Copyright Language - Added `#Program Info` - Added all the `allunix` stuff - Added saving the first cmd line variable item to a specific variable, so it doesn't get lost in the code - Made the script auto-installing - Added `trap` line - Changed the `GIT_LOC` var to `gitLoc`

diff --git a/bash/auto-git b/bash/auto-git
--- a/bash/auto-git
+++ b/bash/auto-git
@@ -3,19 +3,51 @@
 # This script is to try to automatically add, commit and push git repos
 # Its also meant to stay as simple as possible.
 
-# You have to input the git repo's location as the first variable on the cmd line
+# You have to input the git repo's location as the first variable
+
+# Copyright © 2017 JPCDI, JPartain89 and Justin Partain
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
+# Program Info
+PROGRAM_NAME="auto-git"
+VERSION="1.0.0"
 
 export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
 [ -e /usr/local/Cellar ] && export PATH="$PATH:/usr/local/Cellar"
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-if [ -n "$1" ]; then
-    GIT_LOC="$1"
-else
-    echo "Need to input the requested git location" | tee -a "${GIT_LOC}/git.log"
+# This makes sure that $1 doesn't get lost in the running of all the code
+if [ $# -ge 1 ]; then cmdLine="$1"; fi
+
+if [[ ! -e "$(command -v allunix)" ]]; then
+    echo "AllUnix file is missing."
+    wget -O - http://bit.ly/jp_allunix | bash
 fi
 
-( git -C "${GIT_LOC}" add . &&
-git -C "${GIT_LOC}" commit -m "Update for $(date)" &&
-git -C "${GIT_LOC}" push ) && echo "Finished gitting at $(date)" >> "${GIT_LOC}/git.log"
+. "$(command -v allunix)"
+git_local_bin_install
+
+trap 'onError $LINENO "$@" >> "${gitLoc}/${PROGRAM_NAME}.log"' ERR
+
+if [ -n "$cmdLine" ]; then
+    gitLoc="$cmdLine"
+else
+    echo "Need to input the requested git location" | tee -a "${gitLoc}/git.log"
+fi
+
+( git -C "${gitLoc}" add . &&
+git -C "${gitLoc}" commit -m "Update for $(date '+%m-%d-%Y %H-%M-%S')" &&
+git -C "${gitLoc}" push ) && echo "Finished gitting at $(date)" >> "${gitLoc}/${PROGRAM_NAME}.log"
