UPdates

diff --git a/bash/auto-handbrake b/bash/auto-handbrake
--- a/bash/auto-handbrake
+++ b/bash/auto-handbrake
@@ -33,8 +33,45 @@ command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
     )
 }
 
+general() {
+    # These are the 'general' file extensions that I use.
+    FIND_ARGS='\( -iname "*avi" -o -iname "*wmv" -o -iname "*mov" -o -iname "*flv"\)'
+}
+AVCHD() {
+    # This is for running against AVCHD
+    FIND_ARGS='-type d -iname "AVCHD"'
+}
+
 PRESET="Apple 1080p60 Surround"
 SOURCE="$FILE"
+
+while (( "$#" )); do
+    case "$1" in
+        -g | --general )
+            current
+            break
+            ;;
+        -d | --directory )
+            DARG=$2 &&
+            not_here &&
+            break
+            ;;
+        -- ) # end argument parsing
+            shift
+            break
+            ;;
+        -* | --*= ) # unsupported flags
+            echo "Error: Unsupported flag $1" >&2;
+            help;
+            die "$@"
+            ;;
+        * ) # preserve positional arguments
+            PARAMS="$PARAMS $1"
+            shift
+            ;;
+    esac
+done
+
 
 while [[ "$?" -ge 1 ]]; do
     case "$FILE" in
@@ -51,4 +88,4 @@ while IFS= read -r line; do
 
     rm "$line"
 
-done < <(find "$SOURCE" \( -iname "*avi" -o -iname "*wmv" -o -iname "*mov" -o -iname "*flv" \) -exec echo {} \; )
+done < <(find "$SOURCE" "${FIND_ARGS}" -exec echo {} \; )
