Tests

diff --git a/bash/auto-gmvault b/bash/auto-gmvault
--- a/bash/auto-gmvault
+++ b/bash/auto-gmvault
@@ -14,8 +14,23 @@ gmACCOUNTS=(
     subkinkyboi89
 )
 
-for i in "${gmACCOUNTS[@]}"; do
-    /usr/local/bin/gmvault sync "${i}@gmail.com" -d "/Volumes/RAID_EXT/backup/gmvault/${i}/" -e -m &  echo ""
-    spinner $!
-    printf "done!\n";
-done || echo "Received an error. Exiting... " exit 1;
+function SYNCING() {
+    for i in "${gmACCOUNTS[@]}"; do
+        /usr/local/bin/gmvault sync "${i}@gmail.com" -d "/Volumes/RAID_EXT/backup/gmvault/${i}/" -t "$SYNC_TYPE"-e -m &  echo ""
+        spinner $!
+        printf "done!\n";
+    done || echo "Received an error. Exiting... " exit 1;
+}
+
+if [ $# -lt 1 ]; then 1=full ; fi
+
+while [ $# -ge 1 ]; do
+    case "$1" in
+        full )
+            SYNC_TYPE=full; SYNCING
+        ;;
+        quick )
+            SYNC_TYPE=quick; SYNCING
+        ;;
+    esac
+done
