UPdates

diff --git a/bash/auto-handbrake b/bash/auto-handbrake
--- a/bash/auto-handbrake
+++ b/bash/auto-handbrake
@@ -36,10 +36,7 @@ command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
 
 HBCLI="$(command -v HandBrakeCLI)"
 
-if [[ ! -x "$HBCLI" ]]; then
-    echo "No HandBrakeCLI is installed. Fix!"
-    exit 1
-fi
+test -x "$HBCLI" || die "Looks like HandBrakeCLI is missing."
 
 general() {
     # These are the 'general' file extensions that I use.
