Testing different cli parsing

diff --git a/bash/avchd-to-mp4 b/bash/avchd-to-mp4
--- a/bash/avchd-to-mp4
+++ b/bash/avchd-to-mp4
@@ -5,7 +5,7 @@
 
 PROGRAM_NAME="avchd-to-mp4"
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-FILE="$1"
+PARAMS=""
 
 die() {
     echo "$PROGRAM_NAME: $1" >&2
@@ -27,9 +27,9 @@ $PROGRAM_NAME [ -c | --current ] | [ -d | --directory ]  [directory location]
 
 This script is to find the MTS files inside the AVCHD container and turn them into mp4 files.
 EOF
-#    -o | --output    :  Its best to use this for specifying where you want
-#                     :  the new mp4 files to sit. Otherwise, they'll be
-#                     :  created next to the MTS files.
+    #    -o | --output    :  Its best to use this for specifying where you want
+    #                     :  the new mp4 files to sit. Otherwise, they'll be
+    #                     :  created next to the MTS files.
 
 }
 
@@ -47,14 +47,29 @@ command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
     )
 }
 
-if [[ "$?" -lt 1 ]]; then help && die "$@"; fi
-
-while [[ "$?" -ge 1 ]]; do
-    case "$FILE" in
-        --current | -c ) current;;
-        -d | --directory ) not_here;;
-        -h ) help;;
-        * ) help;;
+while (( "$#" )); do
+    case "$1" in
+        -c | --current )
+            CARG=$(PWD);
+            current
+            ;;
+        -d | --directory )
+            DARG=$2;
+            not_here
+            ;;
+        -- ) # end argument parsing
+            shift
+            break
+            ;;
+        -* | --*= ) # unsupported flags
+            echo "Error: Unsupported flag $1" >&2;
+            help;
+            die "$@"
+            ;;
+        * ) # preserve positional arguments
+            PARAMS="$PARAMS $1"
+            shift
+            ;;
     esac
 done
 
@@ -62,7 +77,7 @@ current() {
 
     IFS=$(echo -en "\n\b")
 
-    for i in *.MTS; do
+    for i in "${CARG}"/*.MTS; do
 
         ffmpeg -i "$i" -vcodec mpeg4 -b:v 15M -acodec libmp3lame -b:a 192k "${i}.mp4"
 
@@ -75,5 +90,5 @@ not_here() {
 
         ffmpeg -i "${line}" -vcodec mpeg4 -b:v 15M -acodec libmp3lame -b:a 192k "${output}" < /dev/null
 
-    done < <(find "${FILE}" -iname "*.MTS" -exec echo {} \; )
+    done < <(find "${DARG}" -iname "*.MTS" -exec echo {} \; )
 }
