Updates

diff --git a/bash/backup_plex b/bash/backup_plex
--- a/bash/backup_plex
+++ b/bash/backup_plex
@@ -23,28 +23,35 @@ PROGRAM_NAME="backup_plex"
 REPO_NAME="generalscripts"
 VERSION="1.0.0"
 
+# Declaring and sourcing my functions script
+FUNCTONS="${HOME}/.config/functions/bash_functions"
+. "${FUNCTONS}"
+
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-# This "auto-installs" git-auto into /usr/local/bin for ya!
-command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
-    (
-        if [ -x "${DIR}/${PROGRAM_NAME}" ]; then
-            sudo ln -svf "${DIR}/${PROGRAM_NAME}" "/usr/local/bin/${PROGRAM_NAME}"
-            sudo chmod -R 0775 "/usr/local/bin/${PROGRAM_NAME}"
-        else
-            echo "For some reason, linking $PROGRAM_NAME to /usr/local/bin,"
-            echo "failed. My apologies for not being able to figure it out..."
-            exit 1
-        fi
-    )
-}
+__link_install
+# This "auto-installs"  into /usr/local/bin for ya!
+#command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
+#    (
+#        if [ -x "${DIR}/${PROGRAM_NAME}" ]; then
+#            sudo ln -svf "${DIR}/${PROGRAM_NAME}" "/usr/local/bin/${PROGRAM_NAME}"
+#            sudo chmod -R 0775 "/usr/local/bin/${PROGRAM_NAME}"
+#        else
+#            echo "For some reason, linking $PROGRAM_NAME to /usr/local/bin,"
+#            echo "failed. My apologies for not being able to figure it out..."
+#            exit 1
+#        fi
+#    )
+#}
 
-die() {
-    echo "$PROGRAM_NAME: $1" >&2
-    exit "${2:-1}"
-}
+__die
+#die() {
+#    echo "$PROGRAM_NAME: $1" >&2
+#    exit "${2:-1}"
+#}
 
-trap 'die "Trap Called"' SIGHUP SIGINT SIGTERM
+#trap 'die "Trap Called"' SIGHUP SIGINT SIGTERM
+__trap
 
 PATH=/usr/local/opt/python3/bin:/usr/local/opt/python3/libexec/bin:/usr/local/opt/python@2/bin:/usr/local/opt/python/bin:/usr/local/opt/python/libexec/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/Cellar:/usr/local/MacGPG2/bin:/usr/local/opt/go/libexec/bin:/Users/jpartain89/.bashhub/bin
 
@@ -54,13 +61,16 @@ __BACKUP_FILE="com.plexapp.plexmediaserver.plist"
 BACKUP_FROM_FILES="${__BACKUP_FROM}/Preferences/${__BACKUP_FILE}"
 BACKUP_FROM_DIR="${__BACKUP_FROM}/ApplicationSupport/Plex Media Server"
 BACKUP_TO_FILE="${__BACKUP_TO}/PlexBackup_$(date +"%m-%d-%Y").tar.gz"
-LOGFILE="/usr/local/var/log/PlexBackup"
+LOGDIR="/usr/local/var/log/PlexBackup"
 
 TAR="$(command -v tar)"
 
-if [[ ! -d "${LOGFILE}" ]]; then mkdir "${LOGFILE}"; fi
+# This is to create the log directory, just in case
+if [[ ! -d "${LOGDIR}" ]]; then mkdir "${LOGDIR}"; fi
 
+# This is the actual TAR step
 "${TAR}" vcfz "${BACKUP_TO_FILE}" "${BACKUP_FROM_DIR}" \
-    > "${LOGFILE}/$(date +"%m-%d-%Y").log" 2>&1
+    > "${LOGDIR}/$(date +"%m-%d-%Y").log" 2>&1
 
+# This is to copy the PLIST file for macOS
 cp "${BACKUP_FROM_FILES}" "${__BACKUP_TO}/${__BACKUP_FILE}_$(date +"%m-%d-%Y")"
