Update for 07-06-2022 16-10-27

diff --git a/bash/ssdc b/bash/ssdc
--- a/bash/ssdc
+++ b/bash/ssdc
@@ -9,18 +9,31 @@ REPO_NAME="generalscripts"
 DF_LOCATION="${HOME}/git/docker_directory"
 DF=docker-compose.yml
 DF_CHILD_LOCATIONS=$(cat ${DF_LOCATION}/ssdc.conf)
-eval ~/git/generalscripts/bash/functions/bash_functions
-# "${DF_LOCATION}/ssdc.conf"
-
-_logging;
 
 # Program based Variables
 DOCKER="$(command -v docker)"
 DOCKER_CMD="${DOCKER} compose -f"
 
+die() {
+    cd ${DIR}
+    echo "$PROGRAM_NAME: $1" >&2
+    exit "${2:-1}"
+}
+
 trap "die 'trap called'" SIGHUP SIGINT SIGTERM
 
-_link_install
+command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
+    (
+        if [ -x "${DIR}/${PROGRAM_NAME}" ]; then
+            sudo ln -svf "${DIR}/${PROGRAM_NAME}" "/usr/local/bin/${PROGRAM_NAME}"
+            sudo chmod -R 0775 "/usr/local/bin/${PROGRAM_NAME}"
+        else
+            echo "For some reason, linking $PROGRAM_NAME to /usr/local/bin,"
+            echo "failed. My apologies for not being able to figure it out..."
+            exit 1
+        fi
+    )
+}
 
 git_pull() {
     # Pulls the main repo for us
