Update for 09-05-2022 20-31-34

diff --git a/bash/synctorrents b/bash/synctorrents
--- a/bash/synctorrents
+++ b/bash/synctorrents
@@ -1,24 +1,50 @@
 #!/usr/bin/env bash
 set -e
- 
-#login information for your remote host, no quotes
-login=seedit4me
- 
-#password information for your remote host, no quotes
-pass=hTUq6aEYcJQ!
- 
-#host info for your remote host. include full URL standard format is sftp://ftp.servername.com
-host=sftp://137.nl19.seedit4.me
- 
+
+PROGRAM_NAME=synctorrents
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+REPO_NAME="generalscripts"
+
+die() {
+    cd ${DIR}
+    echo "$PROGRAM_NAME: $1" >&2
+    exit "${2:-1}"
+}
+
+trap "die 'trap called'" SIGHUP SIGINT SIGTERM
+
+command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
+    (
+        if [ -x "${DIR}/${PROGRAM_NAME}" ]; then
+            sudo ln -svf "${DIR}/${PROGRAM_NAME}" "/usr/local/bin/${PROGRAM_NAME}"
+            sudo chmod -R 0775 "/usr/local/bin/${PROGRAM_NAME}"
+        else
+            echo "For some reason, linking $PROGRAM_NAME to /usr/local/bin,"
+            echo "failed. My apologies for not being able to figure it out..."
+            exit 1
+        fi
+    )
+}
+
+
+# login information for your remote host, no quotes
+login=
+
+# password information for your remote host, no quotes
+pass=
+
+# host info for your remote host. include full URL standard format is sftp://ftp.servername.com
+host=
+
 #remote location where your finished downloads are on your seedbox
-remote_dir=/home/seedit4me/torrents/rtorrent/
- 
+remote_dir=
+
 #local directory where you are storing your downloads for further processing
-local_dir=/media/localDownloads/syncthing
- 
+local_dir=/
+
 # The next few lines checks if lftp is running and stops the script if so.
 # Will also show the PID if you want to kill the lftp from running manually (although you can use pkill lftp)
- 
+
 checkifrunning=$(ps -aux | grep [l]ftp | awk '{print $2}')
 if [[ $checkifrunning ]]; then
   echo "Synctorrent is running already. PID " $checkifrunning
