Update for 07-21-2024 18-30-57

diff --git a/bash/transcode-wrap b/bash/transcode-wrap
--- a/bash/transcode-wrap
+++ b/bash/transcode-wrap
@@ -9,7 +9,11 @@ PROGRAM_NAME="transcode-wrap"
 REPO_NAME="generalscripts"
 
 PIPE="/tmp/${PROGRAM_NAME}.out"
-mkfifo "${PIPE}"
+if [[ ! -f "${PIPE}" ]]; then
+  mkfifo "${PIPE}"
+else
+  continue
+fi
 
 # Start logging to journal
 systemd-cat < "${PIPE}" &
@@ -35,6 +39,11 @@ command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
       exit 1
     fi
   )
+}
+
+die () {
+  rm "${PIPE}" && 
+  echo "$*" >&2; exit 2; }  # complain to STDERR and exit with error
 }
 
 trap "die 'trap called'" SIGHUP SIGINT SIGTERM
