Update for 02-02-2022 01-50-50

diff --git a/bash/transcode-wrap b/bash/transcode-wrap
--- a/bash/transcode-wrap
+++ b/bash/transcode-wrap
@@ -1,16 +1,96 @@
 #!/usr/bin/env bash
 set -e
 
+#This is to call 'transcode-video' in batch-form
+
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+PROGRAM_NAME="transcode-wrap"
+REPO_NAME="generalscripts"
+
+die() {
+    echo "${PROGRAM_NAME}: $1" >&2
+    exit "${2:-1}"
+}
+
+# This tests for gnu-getopt, as thats needed to run
+if [ -f /usr/local/opt/gnu-getopt/bin/getopt ]; then
+    GETOPT="/usr/local/opt/gnu-getopt/bin/getopt"
+    if [ "$("$GETOPT" --test; echo $?)" != 4 ]; then
+        die "You seem to have the wrong version of gnu-getopt?
+        Please investigate and have the proper one installed."
+    fi
+else
+    die "Seems you're missing the required gnu-getopt program.
+    Please install using brew install gnu-getopt."
+fi
+
+# This "auto-installs" git-auto into /usr/local/bin for ya!
+command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
+  (
+    if [ -x "${DIR}/${PROGRAM_NAME}" ]; then
+      sudo ln -svf "${DIR}/${PROGRAM_NAME}" "/usr/local/bin/${PROGRAM_NAME}"
+      sudo chmod -R 0775 "/usr/local/bin/${PROGRAM_NAME}"
+    else
+      echo "For some reason, linking $PROGRAM_NAME to /usr/local/bin,"
+      echo "failed. My apologies for not being able to figure it out..."
+      exit 1
+    fi
+  )
+}
+
 TRANSCODE="$(command -v transcode-video)"
 
 if [[ "${TRANSCODE}" == "" ]]; then
-    echo "You don't have the necessary program. Exiting."
-    exit 1
+  echo "You don't have the necessary program."
+  echo "You need to install ${TRANSCODE}"
+  exit 1
 fi
 
-while IFS= read -r line; do
-    FILE_NAME="$(basename "${line}")"
-    BASENAME="$(dirname "${line}")"
-    mkdir "${BASENAME}/processed"
-    "${TRANSCODE}" --mp4 --quick "${line}" -o "${BASENAME}/processed/${FILE_NAME}"
-done< <(find "." \( -iname "*.mkv" -o -iname "*.mp4" \) -exec echo {} \; )
+main() {
+  while IFS= read -r file; do
+    for i in "$file"; do
+      cd $(dirname "$i") &&
+      transcode-video --quick --mp4 "$(basename "$i")" \
+        "$(basename "${i%${EXT}}mp4")" &&
+      cd "${DIR}";
+    done;
+  done< <(find ${LOCATION} -iname "*.${EXT}" -exec echo {} \;)
+}
+
+SHORT=le
+LONG=location,ext,
+
+OPTS=$(${GETOPT} --options ${SHORT} --long ${LONG} --name "$0" -- "$@")
+
+if [ $? != 0 ] ; then
+  die "Failed to parse options...exiting." >&2
+fi
+
+eval set -- "${OPTS}"
+
+while true; do
+  case "$1" in
+    -l | --location )
+      LOCATION="${2}";
+      shift;
+      break;
+      ;;
+    -e | --extension )
+      EXT="${2}"
+      shift;
+      break;
+      ;;
+    -h | --help )
+      usage
+      exit 0
+      ;;
+    -- )
+      shift
+      break
+      ;;
+  esac
+done
+
+main
+
+exit 0
